# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null

nelmio_cors:
    defaults:
        allow_origin: ['https://start-zup.wladev.fr']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://start-zup.wladev.fr']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600

